# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
# Dependencies
markdown:
  redcarpet
  
highlighter:	
  rouge  

permalink:           pretty
# relative_permalinks: true

# Setup
title:               Techblog
tagline:             'For Learner'
description:         'Welcome to the blog!.
If you checked out the About page then you know my name. Looking at the front page, you probably saw that this is a Programming and Technological blog. Glad you came by.'
url:                 https://knlsharma.github.io
baseurl:             '/blog'
paginate:            5

# About/contact
author:
  name:              Kunal Sharma 
  url:               https://knlsharma.github.io
  email:             techblog@gmail.com

# Custom vars
version:             1.0.0
